#======================================#
# Cherry    ©2019 와니
#======================================#

# cherry.wnynya.com
#
# 체리 플러그인 설정 파일입니다.
#
# 변경 및 저장 후 cherry reload 혹은 cherry reloadopt 명령어를 사용하여 적용하십시오.





#======================================#
# 이벤트 설정 [1.2.4]
#======================================#

# 텍스트 포멧
#
# {name}          : 플레이어 이름
# {displayname}   : 플레이어 표시 이름
# {msg}           : 메시지 (채팅 포멧에만 사용됨)
# {prefix}        : 플레이어 접두사 (Vault 연동)
# {suffix}        : 플레이어 접미사 (Vault 연동)
# {fromserver}    : 출발 서버 이름 (번지코드 플러그인 연동)
# {gotoserver}    : 도착 서버 이름 (번지코드 플러그인 연동)
# &1-f,r,l,m,n,o,k: 컬러코드 및 텍스트 효과

event:
  #===== 플레이어 서버 접속 시 이벤트
  join:
    # 플레이어 서버 접속 시 플레이어 목록의 이름을 설정합니다.
    setTabList:
      enable: true
      format: "&r{prefix}&r{displayname}&r{suffix}"

    # 서버 접속 시 플레이어 입장 메시지를 설정합니다.
    setMessage:
      # 플레이어 채팅
      playerChat:
        enable: true
        format: "&r&f{prefix}{displayname}{suffix} &r&7joined the game"
      # 플레이어 액션바
      playerActionBar:
        enable: false
        format: "&r&f{prefix}{displayname}{suffix} &r&fjoined the game"
      # 콘솔
      console:
        enable: false
        format: "&r{prefix}{displayname}{suffix} &rjoined the game"

    # 플레이어가 접속할 때 플레이어를 지정된 위치로 이동시킬 지 설정합니다.
    moveToSpawn:
      enable: false

  #===== 플레이어 서버 접속 종료 시 이벤트
  quit:
    # 서버 접속 종료 시 플레이어 퇴장 메시지를 설정합니다.
    setMessage:
      # 플레이어 채팅
      playerChat:
        enable: true
        format: "&r&f{prefix}{displayname}{suffix} &r&7left the game"
      # 플레이어 액션바
      playerActionBar:
        enable: false
        format: "&r&f{prefix}{displayname}{suffix} &r&fleft the game"
      # 콘솔
      console:
        enable: false
        format: "&r{prefix}{displayname}{suffix} &rleft the game"

  #===== 플레이어 채팅 시 이벤트
  chat:
    # 플레이어가 채팅할 때 채팅 형식을 설정합니다.
    setFormat:
      enable: true
      format: "&r&f{prefix}{displayname}{suffix}&r&f: &r&f{msg}"
    # 플레이어가 채팅할 때 텍스트 효과를 적용항 지 설정합니다.
    effect:
      enable: true
    # 플레이어가 채팅할 때 Vault 채팅과 연동하여 출력할 지 설정합니다.
    vault:
      enable: true

  #===== 플레이어 네트워크 접속 시 이벤트
  networkjoin:
    # 플레이어 네트워크에 접속 시 메시지를 설정합니다.
    setMessage:
      # 플레이어 채팅
      playerChat:
        enable: false
        format: "&r&f{prefix}{displayname}{suffix} &r&8joined the server"
      # 콘솔
      console:
        enable: true
        format: "&r{name} &rjoined the server"

  #===== 플레이어 네트워크 접속 종료 시 이벤트
  networkquit:
    # 플레이어 네트워크에 접속 종료 시 메시지를 설정합니다.
    setMessage:
      # 플레이어 채팅
      playerChat:
        enable: false
        format: "&r&f{prefix}{displayname}{suffix} &r&7left the server"
      # 콘솔
      console:
        enable: true
        format: "&r{name} &rleft the server"

  #===== 플레이어 네트워크 서버 변경 입장 시 이벤트
  switchjoin:
    # 네트워크 서버 변경 시 플레이어 입장 메시지를 설정합니다.
    setMessage:
      # 콘솔
      console:
        enable: true
        # {displayname}, {prefix}, {suffix} 사용 불가
        format: "&r{name} &rjoin from {fromserver}"

  #===== 플레이어 네트워크 서버 변경 퇴장 시 이벤트
  switchquit:
    # 네트워크 서버 변경 시 플레이어 퇴장 메시지를 설정합니다.
    setMessage:
      # 플레이어 채팅
      playerChat:
        enable: true
        format: "&r&f{prefix}{displayname}{suffix} &r&7left for {gotoserver}"
      # 콘솔
      console:
        enable: true
        format: "&r{name} &rleft for the {gotoserver}"


#======================================#
# 플레이어 메타 기본값 [1.2.4]
#======================================#

playermeta:
  function:
    wand:
      enable: true
      data: "actionbar"
    notetool:
      enable: true

#======================================#
# 플러그인 기능 동작 설정 [1.2.4
#======================================#

function:
  wand: true
  portal: true

#======================================#
# 완드 설정 [1.2.4]
#======================================#

wand:
  undo-limit: 50

  edit:
    normal-item: SWEET_BERRIES

  brush:
    normal-item: SPECTRAL_ARROW
    physics-item: ARROW
    max-radius: 10

#======================================#
# 포탈 설정 [1.2.4]
#======================================#

portal:

#======================================#
# 웹소켓 설정 [1.2.4]
#======================================#

websocket:
  enable: false
  host: ""
  name: ""
  auth: ""
  path: ""
  event:
    player:
      join: false
      quit: false
      chat: false
      command: false

    console:
      command: true

    commandblock:
      command: false


#======================================#
# 번지코드 설정 [1.2.4]
#======================================#

bungeecord:
  enable: false
  fallback: ""

#======================================#
# 업데이트 설정 [1.2.4]
#======================================#

updater:
  type: "dev"
  auto: true
  show-msg: true





#======================================#
debug: false
config:
  version: "1.2.4"
bomber: true
#======================================#