#======================================#
# Cherry    ©2019-2020 와니
#======================================#

# cherry.wnynya.com
#
# 체리 플러그인 설정 파일입니다.
#
# 변경 및 저장 후 cherry reload 혹은 cherry reloadopt 명령어를 사용하여 적용하십시오.





#======================================#
# 이벤트 설정 [1.2.9]
#======================================#

# 텍스트 포멧
#
# {name}          : 플레이어 이름
# {displayname}   : 플레이어 표시 이름
# {msg}           : 메시지 (채팅 포멧에만 사용됨)
# {prefix}        : 플레이어 접두사 (Vault 연동)
# {suffix}        : 플레이어 접미사 (Vault 연동)
# {fromserver}    : 출발 서버 이름 (번지코드 플러그인 연동)
# {gotoserver}    : 도착 서버 이름 (번지코드 플러그인 연동)
# &1-f,r,l,m,n,o,k: 기본 텍스트 효과
# #XXXXXX;        : HEX 코드 색상
# rgb000,000,000; : RGB 코드 색상

event:

  #===== 플레이어 서버 접속 이벤트
  join:

    # 플레이어 서버 접속 시 플레이어 목록의 이름을 설정합니다.
    list:
      enable: false
      format: "&r{prefix}&r{displayname}&r{suffix}"

    # 서버 접속 시 플레이어 입장 메시지를 설정합니다.
    msg:
      # 일반적인 서버 접속 시
      normal:
        # 플레이어 채팅
        chat:
          enable: false
          format: "&r&f{prefix}{displayname}{suffix} &r&7joined the game"
          # 접속하는 당사자 플레이어에게도 메시지가 보일 지 설정합니다.
          targetPlayer: false
        # 콘솔
        console:
          enable: false
          format: "&r{prefix}{displayname}{suffix} &rjoined the game"
      # 서버 변경 시 (Cherry-BungeeCord 필요)
      change:
        chat:
          enable: false
          format: "&r&f{prefix}{displayname}{suffix} &r&7join from {fromserver}"
          # 접속하는 당사자 플레이어에게도 메시지가 보일 지 설정합니다.
          targetPlayer: false
        # 콘솔
        console:
          enable: false
          # {displayname}, {prefix}, {suffix} 사용 불가
          format: "&r{name} &rjoin from {fromserver}"

    # 서버 접속 시 플레이어 입장 사운드를 설정합니다.
    sound:
      enable: false
      sound: "BLOCK_NOTE_BLOCK_BELL"
      soundCategory: "MASTER"
      volume: 1.0
      pitch: 1.0
      # 접속하는 당사자 플레이어에게도 사운드가 들릴 지 설정합니다.
      targetPlayer: true

    # 플레이어가 접속할 때 플레이어를 지정된 스폰 위치로 이동시킬 지 설정합니다.
    moveToSpawn:
      enable: false

  #===== 플레이어 서버 퇴장 이벤트
  quit:

    # 서버 퇴장시 플레이어 퇴장 메시지를 설정합니다.
    msg:
      # 일반적인 서버 퇴장 시
      normal:
        # 플레이어 채팅
        chat:
          enable: false
          format: "&r&f{prefix}{displayname}{suffix} &r&7left the game"
        # 콘솔
        console:
          enable: false
          format: "&r{prefix}{displayname}{suffix} &rleft the game"
      # 서버 변경 시 (Cherry-BungeeCord 필요)
      change:
        # 플레이어 채팅
        chat:
          enable: false
          format: "&r&f{prefix}{displayname}{suffix} &r&7left for {gotoserver}"
        # 콘솔
        console:
          enable: false
          format: "&r{name} &rleft for the {gotoserver}"

    # 서버 퇴장 시 플레이어 입장 사운드를 설정합니다.
    sound:
      enable: false
      sound: "BLOCK_NOTE_BLOCK_BASS"
      soundCategory: "MASTER"
      volume: 1.0
      pitch: 0.5

  #===== 플레이어 채팅 시 이벤트
  chat:

    # 플레이어가 채팅할 때 채팅 형식을 설정합니다.
    msg:
      # 일반적인 채팅 시
      normal:
        chat:
          enable: false
          format: "&r&f{prefix}{displayname}{suffix}&r&f: &r&f{msg}"
        console:
          enable: false
          format: "&r{prefix}{displayname}{suffix}&r: &r{msg}"
      # 채널 연결 채팅 시 (Cherry-BungeeCord 필요)
      bungeecord:
        channel: "CherryDefault"
        chat:
          enable: false
          format: "&r&7[{server}] &r&f{prefix}{displayname}{suffix}&r&f: &r&f{msg}"
        console:
          enable: false
          format: "&r[{server}] &r{prefix}{displayname}{suffix}&r: &r{msg}"

    # 플레이어가 채팅할 때 텍스트 효과를 적용할 지 설정합니다.
    effect:
      enable: false


#======================================#
# 플레이어 메타 기본값 [1.2.6]
#======================================#

playermeta:
  function:
    wand:
      enable: true
      data: "actionbar"
    notetool:
      enable: true

#======================================#
# 완드 설정 [1.2.6]
#======================================#

wand:
  enable: true

  undo-limit: 50

  edit:
    normal-item: SWEET_BERRIES

  brush:
    normal-item: SPECTRAL_ARROW
    max-radius: 10

#======================================#
# 포탈 설정 [1.2.6]
#======================================#

portal:
  enable: true

#======================================#
# 터미널 설정 [1.2.6]
#======================================#

terminal:
  enable: false
  # ws://
  host: ""
  name: ""
  auth: ""
  path: ""
  event:
    player:
      join: false
      quit: false
      chat: false
      command: false

    console:
      command: true

    commandblock:
      command: false

  log:

    console:
      msg:
        enable: true
      command:
        enable: true

    player:
      msg:
        enable: true

#======================================#
# 번지코드 설정 [1.2.4]
#======================================#

bungeecord:
  enable: false
  fallback: ""

#======================================#
# 업데이트 설정 [1.2.4]
#======================================#

updater:
  enable: true
  type: "dev"
  auto: false
  show-msg: false

#======================================#
# 지원 설정 [1.2.6]
#======================================#

vault-support:
  enable: false
  chat: true

cucumbery-support:
  enable: true


#======================================#
debug: false
config:
  version: "1.2.9-dev-1"
bomber: false
java-8-legacy: false
fuck: "yeaH"
#======================================#