name: Cherry
version: 1.18-dev
main: io.wany.cherry.Cherry

description: Cherry
author: Wany
website: https://cherry.wany.io

api-version: 1.18
softdepend: [CoreProtect, Cucumbery, Vault]
loadbefore:
  - CoreProtect
  - Cucumbery
  - Essentials
  - HolographicDisplays
  - LuckPerms
  - mcMMO
  - NoteBlockAPI
  - PlugMan
  - ProtocolLib
  - QuickShop
  - Vault
  - VoxelSniper
  - WorldEdit
  - WorldGuard

commands:

  cherry:
    permission: cherry.command.cherry
    aliases: [c]

  wandedit:
    permission: cherry.command.wand.edit
    aliases: [cwand, we, wand, ww, //]

  wandbrush:
    permission: cherry.command.wand.brush
    aliases: [cbrush, wb, brush]

  portal:
    permission: cherry.command.portal
    aliases: [cportal]

  menu:
    permission: cherry.command.menu
    aliases: [cmenu, apsb, 메뉴, ㅡ두ㅕ]

  throw:
    permission: cherry.command.throw

  troll:
    permission: cherry.command.troll

  bungeeteleport:
    permission: cherry.command.bungeeteleport
    aliases: [btp, gtp, tpb]

  list:
    description: "Close player's opened inventory"
    usage: "/<command> [group|world]"
    permission: cherry.command.list
    aliases: [clist]

  exit:
    description: "Exit the game"
    usage: "/<command>"
    permission: minecraft.command.exit
    aliases: [quit, 나가기, 겜접, gg]

  drop:
    description: "Drop current hand item"
    usage: "/<command> [true|false]"
    permission: minecraft.command.drop

  lid:
    description: "Change block state of lidded block"
    usage: "/<command> [open|close|toggle] [x] [y] [z] [world]"
    permission: minecraft.command.lid

  toggledownfall:
    description: "Toggle downfall"
    usage: "/<command>"
    permission: minecraft.command.toggledownfall

  closeinventory:
    description: "Close player's opened inventory"
    usage: "/<command> [player]"
    permission: minecraft.command.closeinventory
    aliases: [cci]